In [10]:
import numpy as np
from sympy import Matrix
import matplotlib.pyplot as plt
import seaborn as sns

In [23]:

arr = np.array([1,2,3,4,5])

sin_values = np.sin(arr)
print("Sin Value" ,sin_values)

cos_values = np.cos(arr)
print("Cos Values",cos_values)

tan_values = np.tan(arr)
print ("Tan Value : " ,tan_values)

asin_values = np.arcsin(np.clip(arr / np.max(arr), -1, 1))
print ("Reverse Sin Value", asin_values)

acos_values = np.arccos(np.clip(arr/np.max(arr), -1,1 ))
print("Reverse Cos Value :" ,acos_values)

atan_values = np.arctan(arr)
print("Reverse Tan Values : ", atan_values)


exp_values = np.exp(arr)
print("Exponential Values :" ,exp_values)

abs_values = np.abs(arr)
print("Absolute Values : ", abs_values)

sqrt_values = np.sqrt(arr)
print("Squer Values :" , sqrt_values)

rem_values = np.remainder(arr, 3)
print("Remainder values :", rem_values)

temp = np.array([1.5,1.1,1.9])

round_values = np.round(temp)
print("Round Values :", round_values)

floor_value = np.floor(temp)
print ("Floor Values : ", floor_value)

ceil_values = np.ceil(temp)
print("Ceiling Values :",ceil_values)

Sin Value [ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
Cos Values [ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219]
Tan Value :  [ 1.55740772 -2.18503986 -0.14254654  1.15782128 -3.38051501]
Reverse Sin Value [0.20135792 0.41151685 0.64350111 0.92729522 1.57079633]
Reverse Cos Value : [1.36943841 1.15927948 0.92729522 0.64350111 0.        ]
Reverse Tan Values :  [0.78539816 1.10714872 1.24904577 1.32581766 1.37340077]
Exponential Values : [  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
Absolute Values :  [1 2 3 4 5]
Squer Values : [1.         1.41421356 1.73205081 2.         2.23606798]
Remainder values : [1 2 0 1 2]
Round Values : [2. 1. 2.]
Floor Values :  [1. 1. 1.]
Ceiling Values : [2. 2. 2.]


In [25]:
matrix = np.array([[1, 2], [3, 4]])

sin_values = np.sin(matrix)
print("Sin Value" ,sin_values)

cos_values = np.cos(matrix)
print("Cos Values",cos_values)

tan_values = np.tan(matrix)
print ("Tan Value : " ,tan_values)

asin_values = np.arcsin(np.clip(matrix / np.max(matrix), -1, 1))
print ("Reverse Sin Value", asin_values)

acos_values = np.arccos(np.clip(matrix/np.max(matrix), -1,1 ))
print("Reverse Cos Value :" ,acos_values)

atan_values = np.arctan(matrix)
print("Reverse Tan Values : ", atan_values)


exp_values = np.exp(matrix)
print("Exponential Values :" ,exp_values)

abs_values = np.abs(matrix)
print("Absolute Values : ", abs_values)

sqrt_values = np.sqrt(matrix)
print("Squer Values :" , sqrt_values)

rem_values = np.remainder(matrix, 3)
print("Remainder values :", rem_values)

# temp = np.array([1.5,1.1,1.9])

round_values = np.round(matrix)
print("Round Values :", round_values)

floor_value = np.floor(matrix)
print ("Floor Values : ", floor_value)

ceil_values = np.ceil(matrix)
print("Ceiling Values :",ceil_values)


Sin Value [[ 0.84147098  0.90929743]
 [ 0.14112001 -0.7568025 ]]
Cos Values [[ 0.54030231 -0.41614684]
 [-0.9899925  -0.65364362]]
Tan Value :  [[ 1.55740772 -2.18503986]
 [-0.14254654  1.15782128]]
Reverse Sin Value [[0.25268026 0.52359878]
 [0.84806208 1.57079633]]
Reverse Cos Value : [[1.31811607 1.04719755]
 [0.72273425 0.        ]]
Reverse Tan Values :  [[0.78539816 1.10714872]
 [1.24904577 1.32581766]]
Exponential Values : [[ 2.71828183  7.3890561 ]
 [20.08553692 54.59815003]]
Absolute Values :  [[1 2]
 [3 4]]
Squer Values : [[1.         1.41421356]
 [1.73205081 2.        ]]
Remainder values : [[1 2]
 [0 1]]
Round Values : [[1 2]
 [3 4]]
Floor Values :  [[1. 2.]
 [3. 4.]]
Ceiling Values : [[1. 2.]
 [3. 4.]]


In [39]:
from mpmath.libmp.libelefun import MAX_LOG_INT_CACHE
vec = np.array([3, 1, 4, 1, 5, 9, 2, 6])

max_value = np.max(vec)
print(" Max Value : ",max_value)

max_index = np.argmax(vec)
print ("Maxi Index : " ,max_index)

min_value = np.min(vec)
print(" Min Value : ",min_value)

min_index = np.argmin(vec)
print ("Min Index : " ,min_index)

vec_length = len(vec)
print("Vector Length ",vec_length)

sorted_a_vec =np.sort(vec)
print("Assending Order of Vector :",sorted_a_vec)

sorted_d_vec =np.sort(vec)[::-2]
print("Dissending Order of Vector: ",sorted_d_vec)

sum_values =np.sum(vec)
print("Sum of : ",sum_values)

prod_values = np.prod(vec)
print("Product of Vector: ",prod_values)

median_value = np.median(vec)
print("Median is : ",median_value)

mean_value = np.mean(vec)
print("Mean is: ",mean_value)

std_dev = np.std(vec)
print("Standerd Deviation : ",std_dev)



 Max Value :  9
Maxi Index :  5
 Min Value :  1
Min Index :  1
Vector Length  8
Assending Order of Vector : [1 1 2 3 4 5 6 9]
Dissending Order of Vector:  [9 5 3 1]
Sum of :  31
Product of Vector:  6480
Median is :  3.5
Mean is:  3.875
Standerd Deviation :  2.5708704751503917


In [58]:
matrix = np.array([[1, 2, 3], [4, 5, 6]])


sorted_a_vec =np.sort(matrix)
print("Assending Order of Vector :\n",sorted_a_vec)



sorted_d_vec =np.sort(matrix, axis=1)[:,::-1]

print("Dissending Order of Vector: \n",sorted_d_vec)




Assending Order of Vector :
 [[1 2 3]
 [4 5 6]]
Dissending Order of Vector: 
 [[3 2 1]
 [6 5 4]]
