In [2]:
import numpy as np
from sympy import Matrix
import matplotlib.pyplot as plt
import seaborn as sns

In [9]:
from math import tan
scalar = 3.4
arr = np.array([3.3,4.4,5.6,6.1,7.3,8.8,9.2,10.9])

add_values = scalar + arr
print("Addition: ",add_values)

sub_values = scalar - arr
print("Subtraction: ",sub_values)

mul_values = scalar * arr
print("Multiplication: ",mul_values)

div_values = scalar / arr
print("Division: ",div_values)

sq_values = scalar ** arr
print("Square: ",sq_values)

abs_values = np.abs(arr)
print("Absolute: ",abs_values)

exp_values = np.exp(arr)
print("Exponential: ",exp_values)

log_values = np.log(arr)
print("Logarithm: ",log_values)

sin_values = np.sin(arr)
print("Sine: ",sin_values)

cos_values = np.cos(arr)
print("Cosine: ",cos_values)

tan_values= np.tan(arr)
print("Tan: ",tan_values)

asin_values = np.arcsin(np.clip(arr / np.max(arr), -1, 1))
print("Inverse Sine: ",asin_values)

acos_values = np.arccos(np.clip(arr/np.max(arr), -1, 1))
print("Inverse Cosine: ",acos_values)

atan_values = np.arctan(arr)
print("Inverse Tangent: ",atan_values)



Addition:  [ 6.7  7.8  9.   9.5 10.7 12.2 12.6 14.3]
Subtraction:  [ 0.1 -1.  -2.2 -2.7 -3.9 -5.4 -5.8 -7.5]
Multiplication:  [11.22 14.96 19.04 20.74 24.82 29.92 31.28 37.06]
Division:  [1.03030303 0.77272727 0.60714286 0.55737705 0.46575342 0.38636364
 0.36956522 0.31192661]
Square:  [5.67388366e+01 2.18025472e+02 9.46851639e+02 1.74590816e+03
 7.58221499e+03 4.75351064e+04 7.75543276e+04 6.21040890e+05]
Absolute:  [ 3.3  4.4  5.6  6.1  7.3  8.8  9.2 10.9]
Exponential:  [2.71126389e+01 8.14508687e+01 2.70426407e+02 4.45857770e+02
 1.48029993e+03 6.63424401e+03 9.89712906e+03 5.41763638e+04]
Logarithm:  [1.19392247 1.48160454 1.7227666  1.80828877 1.98787435 2.17475172
 2.21920348 2.38876279]
Sine:  [-0.15774569 -0.95160207 -0.63126664 -0.1821625   0.85043662  0.58491719
  0.22288991 -0.99543625]
Cosine:  [-0.98747977 -0.30733287  0.77556588  0.98326844  0.52607752 -0.81109301
 -0.97484362 -0.09542885]
Tan:  [ 0.15974575  3.09632378 -0.81394328 -0.18526223  1.61656142 -0.72114688
 -0.

In [13]:
matrix = np.array([[1.3, -2.1, 3.2, 2.5], [4.4, 5.5, -6.3, 3.2], [-7.6, 8.7, 9.8, 10.3]])

sin_values = np.sin(matrix)
print("Sin Value :",sin_values)

cos_values = np.cos(matrix)
print("Cos value :",cos_values)

tan_values = np.tan(matrix)
print("Tan value :",tan_values)

asin_values =np.arcsin(np.clip(matrix / np.max(matrix), -1, 1))
print("arcsin value :",asin_values)

acos_values = np.arccos(np.clip(matrix / np.max(matrix), -1, 1))
print("arcCos value :",acos_values)

atan_values = np.arctan(matrix)
print("atan value :",atan_values)

exp_values = np.exp(matrix)
print("exp value :",exp_values)

log_values = np.log(matrix)
print("log value :",log_values)


Sin Value : [[ 0.96355819 -0.86320937 -0.05837414  0.59847214]
 [-0.95160207 -0.70554033 -0.0168139  -0.05837414]
 [-0.96791967  0.66296923 -0.36647913 -0.76768581]]
Cos value : [[ 0.26749883 -0.5048461  -0.99829478 -0.80114362]
 [-0.30733287  0.70866977  0.99985864 -0.99829478]
 [ 0.25125984 -0.74864665 -0.93042627 -0.64082642]]
Tan value : [[ 3.60210245  1.70984654  0.05847385 -0.7470223 ]
 [ 3.09632378 -0.99558405 -0.01681628  0.05847385]
 [-3.85226569 -0.88555694  0.39388304  1.19796218]]
arcsin value : [[ 0.12655111 -0.20532311  0.31590794  0.24516712]
 [ 0.44137652  0.56330159 -0.65814516  0.31590794]
 [-0.82990029  1.00593006  1.25793341  1.57079633]]
arcCos value : [[1.44424522 1.77611944 1.25488838 1.32562921]
 [1.12941981 1.00749474 2.22894148 1.25488838]
 [2.40069662 0.56486627 0.31286292 0.        ]]
atan value : [[ 0.9151007  -1.12637712  1.26791146  1.19028995]
 [ 1.34731973  1.39094283 -1.41337945  1.26791146]
 [-1.43996893  1.45635602  1.46910748  1.47401228]]
exp value

/tmp/ipykernel_2719/1117642275.py:24: RuntimeWarning: invalid value encountered in log
  log_values = np.log(matrix)
